/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SkillService } from "../skill.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SkillCreateInput } from "./SkillCreateInput";
import { Skill } from "./Skill";
import { SkillFindManyArgs } from "./SkillFindManyArgs";
import { SkillWhereUniqueInput } from "./SkillWhereUniqueInput";
import { SkillUpdateInput } from "./SkillUpdateInput";
import { SkillLevelFindManyArgs } from "../../skillLevel/base/SkillLevelFindManyArgs";
import { SkillLevel } from "../../skillLevel/base/SkillLevel";
import { SkillLevelWhereUniqueInput } from "../../skillLevel/base/SkillLevelWhereUniqueInput";
import { ObjectiveFindManyArgs } from "../../objective/base/ObjectiveFindManyArgs";
import { Objective } from "../../objective/base/Objective";
import { ObjectiveWhereUniqueInput } from "../../objective/base/ObjectiveWhereUniqueInput";
import { FormationFindManyArgs } from "../../formation/base/FormationFindManyArgs";
import { Formation } from "../../formation/base/Formation";
import { FormationWhereUniqueInput } from "../../formation/base/FormationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SkillControllerBase {
  constructor(
    protected readonly service: SkillService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Skill })
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SkillCreateInput,
  })
  async createSkill(@common.Body() data: SkillCreateInput): Promise<Skill> {
    return await this.service.createSkill({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Skill] })
  @ApiNestedQuery(SkillFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async skills(@common.Req() request: Request): Promise<Skill[]> {
    const args = plainToClass(SkillFindManyArgs, request.query);
    return this.service.skills({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Skill })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async skill(
    @common.Param() params: SkillWhereUniqueInput
  ): Promise<Skill | null> {
    const result = await this.service.skill({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Skill })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SkillUpdateInput,
  })
  async updateSkill(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() data: SkillUpdateInput
  ): Promise<Skill | null> {
    try {
      return await this.service.updateSkill({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Skill })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSkill(
    @common.Param() params: SkillWhereUniqueInput
  ): Promise<Skill | null> {
    try {
      return await this.service.deleteSkill({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/skillLevels")
  @ApiNestedQuery(SkillLevelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "read",
    possession: "any",
  })
  async findSkillLevels(
    @common.Req() request: Request,
    @common.Param() params: SkillWhereUniqueInput
  ): Promise<SkillLevel[]> {
    const query = plainToClass(SkillLevelFindManyArgs, request.query);
    const results = await this.service.findSkillLevels(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        level: true,

        collaborator: {
          select: {
            id: true,
          },
        },

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/skillLevels")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async connectSkillLevels(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: SkillLevelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skillLevels: {
        connect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/skillLevels")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async updateSkillLevels(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: SkillLevelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skillLevels: {
        set: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/skillLevels")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async disconnectSkillLevels(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: SkillLevelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skillLevels: {
        disconnect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/objectives")
  @ApiNestedQuery(ObjectiveFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Objective",
    action: "read",
    possession: "any",
  })
  async findObjectives(
    @common.Req() request: Request,
    @common.Param() params: SkillWhereUniqueInput
  ): Promise<Objective[]> {
    const query = plainToClass(ObjectiveFindManyArgs, request.query);
    const results = await this.service.findObjectives(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async connectObjectives(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: ObjectiveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectives: {
        connect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async updateObjectives(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: ObjectiveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectives: {
        set: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/objectives")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async disconnectObjectives(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: ObjectiveWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectives: {
        disconnect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/formations")
  @ApiNestedQuery(FormationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "any",
  })
  async findFormations(
    @common.Req() request: Request,
    @common.Param() params: SkillWhereUniqueInput
  ): Promise<Formation[]> {
    const query = plainToClass(FormationFindManyArgs, request.query);
    const results = await this.service.findFormations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/formations")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async connectFormations(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: FormationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      formations: {
        connect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/formations")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async updateFormations(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: FormationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      formations: {
        set: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/formations")
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "update",
    possession: "any",
  })
  async disconnectFormations(
    @common.Param() params: SkillWhereUniqueInput,
    @common.Body() body: FormationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      formations: {
        disconnect: body,
      },
    };
    await this.service.updateSkill({
      where: params,
      data,
      select: { id: true },
    });
  }
}
