/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SkillLevelListRelationFilter } from "../../skillLevel/base/SkillLevelListRelationFilter";
import { ObjectiveListRelationFilter } from "../../objective/base/ObjectiveListRelationFilter";
import { FormationListRelationFilter } from "../../formation/base/FormationListRelationFilter";

@InputType()
class SkillWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SkillLevelListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SkillLevelListRelationFilter)
  @IsOptional()
  @Field(() => SkillLevelListRelationFilter, {
    nullable: true,
  })
  skillLevels?: SkillLevelListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ObjectiveListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ObjectiveListRelationFilter)
  @IsOptional()
  @Field(() => ObjectiveListRelationFilter, {
    nullable: true,
  })
  objectives?: ObjectiveListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FormationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FormationListRelationFilter)
  @IsOptional()
  @Field(() => FormationListRelationFilter, {
    nullable: true,
  })
  formations?: FormationListRelationFilter;
}

export { SkillWhereInput as SkillWhereInput };
