/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Visualization } from "./Visualization";
import { VisualizationCountArgs } from "./VisualizationCountArgs";
import { VisualizationFindManyArgs } from "./VisualizationFindManyArgs";
import { VisualizationFindUniqueArgs } from "./VisualizationFindUniqueArgs";
import { CreateVisualizationArgs } from "./CreateVisualizationArgs";
import { UpdateVisualizationArgs } from "./UpdateVisualizationArgs";
import { DeleteVisualizationArgs } from "./DeleteVisualizationArgs";
import { Collaborator } from "../../collaborator/base/Collaborator";
import { VisualizationService } from "../visualization.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Visualization)
export class VisualizationResolverBase {
  constructor(
    protected readonly service: VisualizationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "read",
    possession: "any",
  })
  async _visualizationsMeta(
    @graphql.Args() args: VisualizationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Visualization])
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "read",
    possession: "any",
  })
  async visualizations(
    @graphql.Args() args: VisualizationFindManyArgs
  ): Promise<Visualization[]> {
    return this.service.visualizations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Visualization, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "read",
    possession: "own",
  })
  async visualization(
    @graphql.Args() args: VisualizationFindUniqueArgs
  ): Promise<Visualization | null> {
    const result = await this.service.visualization(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Visualization)
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "create",
    possession: "any",
  })
  async createVisualization(
    @graphql.Args() args: CreateVisualizationArgs
  ): Promise<Visualization> {
    return await this.service.createVisualization({
      ...args,
      data: {
        ...args.data,

        collaborator: args.data.collaborator
          ? {
              connect: args.data.collaborator,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Visualization)
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "update",
    possession: "any",
  })
  async updateVisualization(
    @graphql.Args() args: UpdateVisualizationArgs
  ): Promise<Visualization | null> {
    try {
      return await this.service.updateVisualization({
        ...args,
        data: {
          ...args.data,

          collaborator: args.data.collaborator
            ? {
                connect: args.data.collaborator,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Visualization)
  @nestAccessControl.UseRoles({
    resource: "Visualization",
    action: "delete",
    possession: "any",
  })
  async deleteVisualization(
    @graphql.Args() args: DeleteVisualizationArgs
  ): Promise<Visualization | null> {
    try {
      return await this.service.deleteVisualization(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Collaborator, {
    nullable: true,
    name: "collaborator",
  })
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "read",
    possession: "any",
  })
  async getCollaborator(
    @graphql.Parent() parent: Visualization
  ): Promise<Collaborator | null> {
    const result = await this.service.getCollaborator(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
