/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FormationService } from "../formation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FormationCreateInput } from "./FormationCreateInput";
import { Formation } from "./Formation";
import { FormationFindManyArgs } from "./FormationFindManyArgs";
import { FormationWhereUniqueInput } from "./FormationWhereUniqueInput";
import { FormationUpdateInput } from "./FormationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FormationControllerBase {
  constructor(
    protected readonly service: FormationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Formation })
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: FormationCreateInput,
  })
  async createFormation(
    @common.Body() data: FormationCreateInput
  ): Promise<Formation> {
    return await this.service.createFormation({
      data: {
        ...data,

        skill: data.skill
          ? {
              connect: data.skill,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Formation] })
  @ApiNestedQuery(FormationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async formations(@common.Req() request: Request): Promise<Formation[]> {
    const args = plainToClass(FormationFindManyArgs, request.query);
    return this.service.formations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Formation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async formation(
    @common.Param() params: FormationWhereUniqueInput
  ): Promise<Formation | null> {
    const result = await this.service.formation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,

        skill: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Formation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: FormationUpdateInput,
  })
  async updateFormation(
    @common.Param() params: FormationWhereUniqueInput,
    @common.Body() data: FormationUpdateInput
  ): Promise<Formation | null> {
    try {
      return await this.service.updateFormation({
        where: params,
        data: {
          ...data,

          skill: data.skill
            ? {
                connect: data.skill,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,

          skill: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Formation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFormation(
    @common.Param() params: FormationWhereUniqueInput
  ): Promise<Formation | null> {
    try {
      return await this.service.deleteFormation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,

          skill: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
