/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SkillLevel } from "./SkillLevel";
import { SkillLevelCountArgs } from "./SkillLevelCountArgs";
import { SkillLevelFindManyArgs } from "./SkillLevelFindManyArgs";
import { SkillLevelFindUniqueArgs } from "./SkillLevelFindUniqueArgs";
import { CreateSkillLevelArgs } from "./CreateSkillLevelArgs";
import { UpdateSkillLevelArgs } from "./UpdateSkillLevelArgs";
import { DeleteSkillLevelArgs } from "./DeleteSkillLevelArgs";
import { Collaborator } from "../../collaborator/base/Collaborator";
import { Skill } from "../../skill/base/Skill";
import { SkillLevelService } from "../skillLevel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SkillLevel)
export class SkillLevelResolverBase {
  constructor(
    protected readonly service: SkillLevelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "read",
    possession: "any",
  })
  async _skillLevelsMeta(
    @graphql.Args() args: SkillLevelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SkillLevel])
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "read",
    possession: "any",
  })
  async skillLevels(
    @graphql.Args() args: SkillLevelFindManyArgs
  ): Promise<SkillLevel[]> {
    return this.service.skillLevels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SkillLevel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "read",
    possession: "own",
  })
  async skillLevel(
    @graphql.Args() args: SkillLevelFindUniqueArgs
  ): Promise<SkillLevel | null> {
    const result = await this.service.skillLevel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SkillLevel)
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "create",
    possession: "any",
  })
  async createSkillLevel(
    @graphql.Args() args: CreateSkillLevelArgs
  ): Promise<SkillLevel> {
    return await this.service.createSkillLevel({
      ...args,
      data: {
        ...args.data,

        collaborator: args.data.collaborator
          ? {
              connect: args.data.collaborator,
            }
          : undefined,

        skill: args.data.skill
          ? {
              connect: args.data.skill,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SkillLevel)
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "update",
    possession: "any",
  })
  async updateSkillLevel(
    @graphql.Args() args: UpdateSkillLevelArgs
  ): Promise<SkillLevel | null> {
    try {
      return await this.service.updateSkillLevel({
        ...args,
        data: {
          ...args.data,

          collaborator: args.data.collaborator
            ? {
                connect: args.data.collaborator,
              }
            : undefined,

          skill: args.data.skill
            ? {
                connect: args.data.skill,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SkillLevel)
  @nestAccessControl.UseRoles({
    resource: "SkillLevel",
    action: "delete",
    possession: "any",
  })
  async deleteSkillLevel(
    @graphql.Args() args: DeleteSkillLevelArgs
  ): Promise<SkillLevel | null> {
    try {
      return await this.service.deleteSkillLevel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Collaborator, {
    nullable: true,
    name: "collaborator",
  })
  @nestAccessControl.UseRoles({
    resource: "Collaborator",
    action: "read",
    possession: "any",
  })
  async getCollaborator(
    @graphql.Parent() parent: SkillLevel
  ): Promise<Collaborator | null> {
    const result = await this.service.getCollaborator(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Skill, {
    nullable: true,
    name: "skill",
  })
  @nestAccessControl.UseRoles({
    resource: "Skill",
    action: "read",
    possession: "any",
  })
  async getSkill(@graphql.Parent() parent: SkillLevel): Promise<Skill | null> {
    const result = await this.service.getSkill(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
