/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OneOnOneMeetingService } from "../oneOnOneMeeting.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OneOnOneMeetingCreateInput } from "./OneOnOneMeetingCreateInput";
import { OneOnOneMeeting } from "./OneOnOneMeeting";
import { OneOnOneMeetingFindManyArgs } from "./OneOnOneMeetingFindManyArgs";
import { OneOnOneMeetingWhereUniqueInput } from "./OneOnOneMeetingWhereUniqueInput";
import { OneOnOneMeetingUpdateInput } from "./OneOnOneMeetingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OneOnOneMeetingControllerBase {
  constructor(
    protected readonly service: OneOnOneMeetingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OneOnOneMeeting })
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OneOnOneMeetingCreateInput,
  })
  async createOneOnOneMeeting(
    @common.Body() data: OneOnOneMeetingCreateInput
  ): Promise<OneOnOneMeeting> {
    return await this.service.createOneOnOneMeeting({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OneOnOneMeeting] })
  @ApiNestedQuery(OneOnOneMeetingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async oneOnOneMeetings(
    @common.Req() request: Request
  ): Promise<OneOnOneMeeting[]> {
    const args = plainToClass(OneOnOneMeetingFindManyArgs, request.query);
    return this.service.oneOnOneMeetings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OneOnOneMeeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async oneOnOneMeeting(
    @common.Param() params: OneOnOneMeetingWhereUniqueInput
  ): Promise<OneOnOneMeeting | null> {
    const result = await this.service.oneOnOneMeeting({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OneOnOneMeeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OneOnOneMeetingUpdateInput,
  })
  async updateOneOnOneMeeting(
    @common.Param() params: OneOnOneMeetingWhereUniqueInput,
    @common.Body() data: OneOnOneMeetingUpdateInput
  ): Promise<OneOnOneMeeting | null> {
    try {
      return await this.service.updateOneOnOneMeeting({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OneOnOneMeeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteOneOnOneMeeting(
    @common.Param() params: OneOnOneMeetingWhereUniqueInput
  ): Promise<OneOnOneMeeting | null> {
    try {
      return await this.service.deleteOneOnOneMeeting({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
