/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OneOnOneMeeting } from "./OneOnOneMeeting";
import { OneOnOneMeetingCountArgs } from "./OneOnOneMeetingCountArgs";
import { OneOnOneMeetingFindManyArgs } from "./OneOnOneMeetingFindManyArgs";
import { OneOnOneMeetingFindUniqueArgs } from "./OneOnOneMeetingFindUniqueArgs";
import { DeleteOneOnOneMeetingArgs } from "./DeleteOneOnOneMeetingArgs";
import { OneOnOneMeetingService } from "../oneOnOneMeeting.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => OneOnOneMeeting)
export class OneOnOneMeetingResolverBase {
  constructor(
    protected readonly service: OneOnOneMeetingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "read",
    possession: "any",
  })
  async _oneOnOneMeetingsMeta(
    @graphql.Args() args: OneOnOneMeetingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [OneOnOneMeeting])
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "read",
    possession: "any",
  })
  async oneOnOneMeetings(
    @graphql.Args() args: OneOnOneMeetingFindManyArgs
  ): Promise<OneOnOneMeeting[]> {
    return this.service.oneOnOneMeetings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => OneOnOneMeeting, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "read",
    possession: "own",
  })
  async oneOnOneMeeting(
    @graphql.Args() args: OneOnOneMeetingFindUniqueArgs
  ): Promise<OneOnOneMeeting | null> {
    const result = await this.service.oneOnOneMeeting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OneOnOneMeeting)
  @nestAccessControl.UseRoles({
    resource: "OneOnOneMeeting",
    action: "delete",
    possession: "any",
  })
  async deleteOneOnOneMeeting(
    @graphql.Args() args: DeleteOneOnOneMeetingArgs
  ): Promise<OneOnOneMeeting | null> {
    try {
      return await this.service.deleteOneOnOneMeeting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
